foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                search:
                    mappings:
                        url: { analyzer: snowball }
                        content: { analyzer: snowball }
                    persistence:
                        driver: propel
                        model: 
                        provider: 
                            service: alphalemon.search_provider.search